# Generated by Django 3.1.5 on 2021-02-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('success', '0003_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('is_do', models.BooleanField(default=False, verbose_name='have done?')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='success.kindtask', verbose_name='kind')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='success.prioritytask', verbose_name='priority')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто автор')),
            ],
        ),
    ]
